# Generated by Django 5.2.2 on 2026-01-12 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100)),
                ('email_usuario', models.EmailField(max_length=254, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('status_usuario', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capinhacore.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=20)),
                ('conta', models.CharField(max_length=20)),
                ('tipo_conta', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='capinhacore.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefone', models.CharField(max_length=20)),
                ('tipo_telefone', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capinhacore.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recompensa', models.DateTimeField(auto_now_add=True)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capinhacore.recompensa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capinhacore.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'recompensa')},
            },
        ),
    ]
