# Generated by Django 5.2.7 on 2026-01-14 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_artistico', models.CharField(max_length=150)),
                ('biografia', models.TextField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_artista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancariaArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=20)),
                ('conta', models.CharField(max_length=30)),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=20)),
                ('artista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_bancaria', to='artists.artista')),
            ],
        ),
    ]
