# Generated by Django 5.2.7 on 2026-01-20 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('creations', '0002_alter_personalizacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='colecao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='colecao',
            name='imagem_destaque',
            field=models.ImageField(blank=True, help_text='Imagem de destaque da coleção', null=True, upload_to='colecoes/'),
        ),
        migrations.AddField(
            model_name='personalizacao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='arte',
            name='arquivo',
            field=models.ImageField(help_text='Arquivo de imagem da arte (PNG, JPG)', upload_to='artes/'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='artista',
            field=models.ForeignKey(help_text='Artista criador da arte', on_delete=django.db.models.deletion.CASCADE, related_name='artes', to='artists.artista'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Arte disponível para uso'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='colecao',
            field=models.ForeignKey(blank=True, help_text='Coleção a qual a arte pertence (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artes', to='creations.colecao'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição ou história da arte'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='nome',
            field=models.CharField(help_text='Nome ou título da arte', max_length=150),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='artista',
            field=models.ForeignKey(help_text='Artista criador da coleção', on_delete=django.db.models.deletion.CASCADE, related_name='colecoes', to='artists.artista'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Coleção visível e disponível'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da coleção de artes'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='nome',
            field=models.CharField(help_text='Nome da coleção', max_length=150),
        ),
        migrations.AlterField(
            model_name='personalizacao',
            name='arte',
            field=models.ForeignKey(blank=True, help_text='Arte que será personalizada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalizacoes', to='creations.arte'),
        ),
        migrations.AlterField(
            model_name='personalizacao',
            name='cor',
            field=models.CharField(blank=True, help_text='Cor da personalização (hex, rgb ou nome)', max_length=50),
        ),
        migrations.AlterField(
            model_name='personalizacao',
            name='fonte',
            field=models.CharField(blank=True, help_text='Fonte do texto (ex: Arial, Roboto)', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalizacao',
            name='preco_extra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Preço adicional desta personalização', max_digits=10),
        ),
        migrations.AlterField(
            model_name='personalizacao',
            name='texto',
            field=models.CharField(blank=True, help_text='Texto personalizado (nome, frase, número)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='arte',
            index=models.Index(fields=['artista', 'ativa'], name='creations_a_artista_e5fa5d_idx'),
        ),
        migrations.AddIndex(
            model_name='arte',
            index=models.Index(fields=['colecao', 'ativa'], name='creations_a_colecao_9fd27e_idx'),
        ),
        migrations.AddIndex(
            model_name='arte',
            index=models.Index(fields=['-criado_em'], name='creations_a_criado__d085ea_idx'),
        ),
        migrations.AddIndex(
            model_name='colecao',
            index=models.Index(fields=['artista', 'ativa'], name='creations_c_artista_9ae786_idx'),
        ),
        migrations.AddIndex(
            model_name='colecao',
            index=models.Index(fields=['-criado_em'], name='creations_c_criado__bfcd80_idx'),
        ),
        migrations.AddIndex(
            model_name='personalizacao',
            index=models.Index(fields=['arte'], name='creations_p_arte_id_aba366_idx'),
        ),
        migrations.AddIndex(
            model_name='personalizacao',
            index=models.Index(fields=['-criado_em'], name='creations_p_criado__9bd383_idx'),
        ),
    ]
