# Generated by Django 5.2.7 on 2026-01-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Foto do produto', null=True, upload_to='produtos/'),
        ),
    ]
